### PR TITLE
remove .vscode

### PR DESCRIPTION
**Pull request by gl91306**
its not neccary for people with vscode and it adds unnecary bookmarks and stuff for people with vscode

### CODE REVIEW

**Comment by HackerDaGreat57** [comment]
I appreciate the effort, but this has been proved unnecessary. `.vscode` is always useful for ending development on one machine and picking up progress on another - plus, the `.vscode` folder is literally about 7 kilobytes, barely anything.

**Comment by gl91306** [comment]
Its not just bookmarks. Its the whold theme. Can you at least delete this bit?: 
```
  "editor.cursorStyle": "block",
  "files.autoSave": "afterDelay",
  "editor.fontFamily": "Cascadia Code, 'Courier New', monospace",
  "editor.tabSize": 2,
  "editor.smoothScrolling": true,
  "editor.suggest.preview": true,
  "editor.minimap.renderCharacters": false,
  "editor.minimap.scale": 1,
  "editor.minimap.showSlider": "mouseover",
  "window.autoDetectColorScheme": true,
  "window.commandCenter": true,
  "window.titleSeparator": " | ",
```
becasue when i opened this on vscode i was confused why my theme went bright mode and why my font size was all weird and why my text caret looked like the one in terminal and that basically changes the theme of the person editing the code(if there using vscode) and its kinda not helpful

**Comment by gl91306** [comment]
made another pr that deletes the theme changing part #12

**Comment by HackerDaGreat57** [comment]
Alright then, I will delete those.

**Pull request closed without merging**
